export default defineEventHandler(() => {
  return [
    {
      wordId: "nei5-you",
      word: "你",
      jyutping: "nei5",
      meaning: "you",
      audioUrl: "",
    },
    {
      wordId: "gwai6-tired",
      word: "攰",
      jyutping: "gwai6",
      meaning: "tired",
      audioUrl: "",
    },
    {
      wordId: "mou5so2wai6-whatever",
      word: "冇所謂",
      jyutping: "mou5 so2 wai6",
      meaning: "whatever / doesn't matter",
      audioUrl: "",
    },
    {
      wordId: "gong2zan1-honestly",
      word: "講真",
      jyutping: "gong2 zan1",
      meaning: "honestly",
      audioUrl: "",
    },
    {
      wordId: "m4gwaai3zi1dak1-no-wonder",
      word: "唔怪之得",
      jyutping: "m4 gwaai3 zi1 dak1",
      meaning: "no wonder",
      audioUrl: "",
    },

    // --- New 20 examples ---

    {
      wordId: "hou2-good",
      word: "好",
      jyutping: "hou2",
      meaning: "good",
      audioUrl: "",
    },
    {
      wordId: "leng3-pretty",
      word: "靚",
      jyutping: "leng3",
      meaning: "pretty / nice",
      audioUrl: "",
    },
    {
      wordId: "zing1-awesome",
      word: "正",
      jyutping: "zing1",
      meaning: "awesome / great",
      audioUrl: "",
    },

    {
      wordId: "ngo5-me",
      word: "我",
      jyutping: "ngo5",
      meaning: "I / me",
      audioUrl: "",
    },
    {
      wordId: "keoi5-he-she",
      word: "佢",
      jyutping: "keoi5",
      meaning: "he / she / they",
      audioUrl: "",
    },
    {
      wordId: "gam2-like-this",
      word: "咁",
      jyutping: "gam2",
      meaning: "like this / so",
      audioUrl: "",
    },
    {
      wordId: "dim2-how",
      word: "點",
      jyutping: "dim2",
      meaning: "how",
      audioUrl: "",
    },
    {
      wordId: "ji1know",
      word: "知",
      jyutping: "zi1",
      meaning: "to know",
      audioUrl: "",
    },
    {
      wordId: "sik1know-how",
      word: "識",
      jyutping: "sik1",
      meaning: "to know how / be familiar with",
      audioUrl: "",
    },
    {
      wordId: "ji6now",
      word: "而家",
      jyutping: "ji4 gaa1",
      meaning: "now",
      audioUrl: "",
    },
    {
      wordId: "taai3-too",
      word: "太",
      jyutping: "taai3",
      meaning: "too / overly",
      audioUrl: "",
    },
    {
      wordId: "hou2doi1-many",
      word: "好多",
      jyutping: "hou2 do1",
      meaning: "a lot / many",
      audioUrl: "",
    },
    {
      wordId: "ji1gaa1-now",
      word: "依家",
      jyutping: "ji1 gaa1",
      meaning: "now (colloquial)",
      audioUrl: "",
    },
    {
      wordId: "maa3-question-particle",
      word: "嗎",
      jyutping: "maa3",
      meaning: "(question particle, written form)",
      audioUrl: "",
    },
    {
      wordId: "laa1-final-particle",
      word: "啦",
      jyutping: "laa1",
      meaning: "(final particle)",
      audioUrl: "",
    },
    {
      wordId: "zau6-then",
      word: "就",
      jyutping: "zau6",
      meaning: "then / right away",
      audioUrl: "",
    },
    {
      wordId: "hai6-is",
      word: "係",
      jyutping: "hai6",
      meaning: "to be / is",
      audioUrl: "",
    },
    {
      wordId: "m4-not",
      word: "唔",
      jyutping: "m4",
      meaning: "not",
      audioUrl: "",
    },
    {
      wordId: "sik6-eat",
      word: "食",
      jyutping: "sik6",
      meaning: "to eat",
      audioUrl: "",
    },
    {
      wordId: "jam2-drink",
      word: "飲",
      jyutping: "jam2",
      meaning: "to drink",
      audioUrl: "",
    },
  ];
});
