import {
  Apple,
  BookOpen,
  BrickWall,
  BriefcaseBusiness,
  Building2,
  Bus,
  Calculator,
  CalendarDays,
  Clock,
  CloudSun,
  Dumbbell,
  FlaskConical,
  Gamepad2,
  Gem,
  Globe2,
  HardHat,
  HeartHandshake,
  HeartPulse,
  House,
  Landmark,
  Mountain,
  Music,
  Newspaper,
  Palette,
  PawPrint,
  Ruler,
  ShieldPlus,
  Shirt,
  Smartphone,
  Smile,
  Sofa,
  Soup,
  Sprout,
  Users,
  Utensils,
  Volume2,
  Zap,
} from '@lucide/vue'
import type { Component } from 'vue'
import { markRaw } from 'vue'

const fallbackTopicIcon = markRaw(BookOpen)

const topicIcons: Record<string, Component> = {
  'survival-essentials': markRaw(ShieldPlus),
  'greetings-polite': markRaw(HeartHandshake),
  'basic-verbs': markRaw(Zap),
  'fruits-vegetables': markRaw(Apple),
  clothing: markRaw(Shirt),
  'dim-sum': markRaw(Soup),
  'restaurant-menu': markRaw(Utensils),
  colours: markRaw(Palette),
  math: markRaw(Calculator),
  'measure-quantities': markRaw(Ruler),
  'time-dates': markRaw(Clock),
  'family-members': markRaw(Users),
  countries: markRaw(Globe2),
  emotions: markRaw(Smile),
  furniture: markRaw(Sofa),
  'sports-fitness': markRaw(Dumbbell),
  weather: markRaw(CloudSun),
  technology: markRaw(Smartphone),
  housing: markRaw(House),
  'transport-travel': markRaw(Bus),
  health: markRaw(HeartPulse),
  'daily-life': markRaw(CalendarDays),
  materials: markRaw(BrickWall),
  animals: markRaw(PawPrint),
  science: markRaw(FlaskConical),
  'hobbies-interests': markRaw(Gamepad2),
  'buildings-local-services': markRaw(Building2),
  business: markRaw(BriefcaseBusiness),
  'jobs-professions': markRaw(HardHat),
  'gemstones-jewellery': markRaw(Gem),
  'landforms-natural-disasters': markRaw(Mountain),
  'news-media': markRaw(Newspaper),
  'plants-gardening': markRaw(Sprout),
  music: markRaw(Music),
  politics: markRaw(Landmark),
  onomatopoeia: markRaw(Volume2),
}

export function getTopicIcon(topicId: string) {
  return topicIcons[topicId] ?? fallbackTopicIcon
}
